### ISSUE TITLE
Instantiating a new SpectateTrigger from within SpectateTrigger#invoke makes for weird debugging

### ISSUE THREAD

**Issue by bradical** [nadirayasmeen/spectate-publish-trigger#2]
In particular, [this pattern](https://github.com/nadirayasmeen/spectate-publish-trigger/blob/6f01b4d358e9d25a54124c36a6b01bcfc30a70f8/src/java/com/hannonhill/emailtrigger/SpectateTrigger.java#L104):

``` java
SpectateTrigger t = new SpectateTrigger();
if(this.parameters.get("apiKey").length() > 0){
   t.setApiKey(this.parameters.get("apiKey"));
}
```

of instantiating a SpectateTrigger from within itself on `invoke()` makes it kind of confusing to figure out what `this` means. Should just pull out most of the functionality into a new class that gets instantiated by the trigger whenever `invoke` is run and is passed the necessary `PublishTriggerInformation` and `parameters` data.

**Comment by bradical** [comment]
Nadira is actively working on this one.

**Comment by nadirayasmeen** [comment]
Sorry forgot to update the issue list: 198e5d4feda25622b4cc07f4d95f02192484887c. I tested this locally & it worked OK (and accidentally sent email to 800 people)

**Comment by bradical** [comment]
@nadirayasmeen I don't think you committed your new file.

**Comment by nadirayasmeen** [comment]
ahhh, forgot about add! 94f4620312deaa3e1a4c86c209fece85298a6790

**Comment by bradical** [comment]
I know these changes didn't introduce this code but this issue seemed like a good place to address it. See comments [here](https://github.com/nadirayasmeen/spectate-publish-trigger/commit/6f01b4d358e9d25a54124c36a6b01bcfc30a70f8#commitcomment-10132389), [here](https://github.com/nadirayasmeen/spectate-publish-trigger/commit/6f01b4d358e9d25a54124c36a6b01bcfc30a70f8#commitcomment-10132423), and [here](https://github.com/nadirayasmeen/spectate-publish-trigger/commit/6f01b4d358e9d25a54124c36a6b01bcfc30a70f8#commitcomment-10132402)

**Comment by bradical** [comment]
Closing this out.
