### ISSUE TITLE
Make trigger skip jobs quickly

### ISSUE THREAD

**Issue by bradical** [nadirayasmeen/spectate-publish-trigger#7]
This includes:
- [x] jobs that should not be processed by the trigger
- [x] jobs that were already processed. Let's find a quick way to check if an email has already gone out.

**Comment by bradical** [comment]
I implemented a really fast page configuration ID check at the beginning of the trigger which should elegantly and quickly handle publishes/unpublishes of non-Spectate page configs. 11adc9c54d2fad0000075170148e28e0a4e0fd4b

Next step is trying to figure out if the email has already been pushed. Thinking about how to fetch the email from Spectate based on name or otherwise check if it exits before buildilng the entire thing and then having it fail with a 206 due to Spectate's unique name constraint.

**Comment by bradical** [comment]
Spoke with @pennyharding and we decided on the following for ensuring that duplicate emails don't get sent:
- Add a new field value: `Email sent to Spectate` (or something like that) to the `send` field in the Data Definition
- On successful creation of the Email in Spectate in the trigger, update that DD field in the page so that it's clear that the Email has been created in Spectate.
- Adapt the code so that it checks the status of that field early and skips the trigger if the page has already been sent to Spectate as an email.

If they want a way to create an email as Draft in Cascade and then send it directly from Cascade later without having to go to Spectate, we can discuss that as part of a different project.

For now, if they create it as draft or send later, they'll need to go into Spectate to take any further action on it.

**Comment by nadirayasmeen** [comment]
Gotcha, sounds good.

**Comment by bradical** [comment]
We got right to the end and realized that using the internal Edit API to update the page wasn't going to work due to [a bug in Cascade](https://hannonhill.jira.com/browse/CSI-804). We're having to re-think this a bit now.

**Comment by bradical** [comment]
As of 47f5a7eaee15fb75d88cad2f6682c54d51dc785b this code is using WS for just the part that updates the page content. It's working for me locally. Next step is deploying to dev and seeing how it goes.

**Comment by bradical** [comment]
Closing this out.
